name: Staging deployment

on:
  pull_request:
      types: [labeled]  

env:
  DOCKER_IMAGE_NAME: Sruinard-azure-ttt
  IMAGE_REGISTRY_URL: ghcr.io
  AZURE_WEBAPP_NAME: Sruinard-ttt-app

jobs:
    build:
      runs-on: ubuntu-latest

      if: contains(github.event.pull_request.labels.*.name, 'stage')
